name: e2e suite

on:
  workflow_dispatch:
  schedule:
    # At 2:00 AM UTC on Monday, Wednesday, and Friday
    - cron: "00 2 * * 1,3,5"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.py"
      - Dockerfile
      - "saleor/**"
      - ".github/workflows/e2e.yml"
      - pyproject.toml
      - uv.lock

env:
  DATABASE_URL: "postgres://saleor:saleor@postgres:5432/saleor"
  SECRET_KEY: ci-test

jobs:
  e2e-tests:
    runs-on: ubuntu-22.04
    container: python:3.12
    name: Run E2E tests

    services:
      postgres:
        image: library/postgres:15-alpine
        env:
          POSTGRES_PASSWORD: saleor
          POSTGRES_USER: saleor
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v5

      - name: Install system dependencies
        run: |
          apt-get install -y libpq-dev

      - uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v6.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --locked

      - name: Run E2E tests
        run: |
          uv run pytest -m "e2e" --junit-xml=e2e-test-results.xml

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@20b595761ba9bf89e115e875f8bc863f913bc8ad # v0.7.2
        with:
          path: e2e-test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: E2E core test results
